CREATE TABLE PROPERTY_COMMENTS (
    ID VARCHAR2(36) PRIMARY KEY,
    PROPERTY_ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL,
    RATING NUMBER(1) DEFAULT 0,
    CONTENT CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMM_PROP FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTIES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMM_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
EXIT;
