-- Drop tables if they exist (clean start)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATIONS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE MESSAGES CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ANALYTICS_REPORTS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE USER_RATINGS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE USER_FOLLOWERS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE PROPERTY_LIKES CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE PROPERTY_IMAGES CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE PROPERTIES CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- USERS Table
CREATE TABLE USERS (
    ID VARCHAR2(36) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255),
    GOOGLE_ID VARCHAR2(100) UNIQUE,
    AVATAR VARCHAR2(255),
    BIO VARCHAR2(500),
    LOCATION VARCHAR2(255),
    IS_ADMIN NUMBER(1) DEFAULT 0,
    ROLE VARCHAR2(20) DEFAULT 'client',
    RATING NUMBER(3,2) DEFAULT 0,
    NUM_REVIEWS NUMBER DEFAULT 0,
    RESET_PASSWORD_TOKEN VARCHAR2(255),
    RESET_PASSWORD_EXPIRES TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PROPERTIES Table
CREATE TABLE PROPERTIES (
    ID VARCHAR2(36) PRIMARY KEY,
    USER_ID VARCHAR2(36) NOT NULL,
    TITLE VARCHAR2(255) NOT NULL,
    DESCRIPTION CLOB NOT NULL,
    PRICE NUMBER NOT NULL,
    LOCATION VARCHAR2(255) NOT NULL,
    PROPERTY_TYPE VARCHAR2(50) NOT NULL,
    CONTACT_METHOD VARCHAR2(50) NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    LATITUDE NUMBER,
    LONGITUDE NUMBER,
    CURRENCY VARCHAR2(10) DEFAULT 'TND',
    IS_FURNISHED NUMBER(1) DEFAULT 0,
    HAS_PARKING NUMBER(1) DEFAULT 0,
    HAS_WIFI NUMBER(1) DEFAULT 0,
    HAS_AC NUMBER(1) DEFAULT 0,
    HAS_HEATING NUMBER(1) DEFAULT 0,
    HAS_BALCONY NUMBER(1) DEFAULT 0,
    ROOM_TYPE VARCHAR2(20),
    OCCUPANTS NUMBER DEFAULT 0,
    TENANTS_SHARING NUMBER DEFAULT 1,
    REQUIRED_CAPACITY NUMBER DEFAULT 1,
    IS_FEATURED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PROP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- PROPERTY_IMAGES Table
CREATE TABLE PROPERTY_IMAGES (
    ID VARCHAR2(36) PRIMARY KEY,
    PROPERTY_ID VARCHAR2(36) NOT NULL,
    IMAGE_URL VARCHAR2(255) NOT NULL,
    CONSTRAINT FK_IMG_PROP FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTIES(ID) ON DELETE CASCADE
);

-- PROPERTY_LIKES Table
CREATE TABLE PROPERTY_LIKES (
    PROPERTY_ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL,
    PRIMARY KEY (PROPERTY_ID, USER_ID),
    CONSTRAINT FK_LIKE_PROP FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTIES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_LIKE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- USER_FOLLOWERS Table
CREATE TABLE USER_FOLLOWERS (
    FOLLOWER_ID VARCHAR2(36) NOT NULL,
    FOLLOWING_ID VARCHAR2(36) NOT NULL,
    PRIMARY KEY (FOLLOWER_ID, FOLLOWING_ID),
    CONSTRAINT FK_FOLLOWER FOREIGN KEY (FOLLOWER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_FOLLOWING FOREIGN KEY (FOLLOWING_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- USER_RATINGS Table
CREATE TABLE USER_RATINGS (
    ID VARCHAR2(36) PRIMARY KEY,
    USER_ID VARCHAR2(36) NOT NULL,
    RATER_ID VARCHAR2(36) NOT NULL,
    RATING NUMBER(1) NOT NULL,
    USER_COMMENT VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RATING_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RATING_RATER FOREIGN KEY (RATER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX IDX_PROP_USER ON PROPERTIES(USER_ID);
CREATE INDEX IDX_PROP_TYPE ON PROPERTIES(PROPERTY_TYPE);
CREATE INDEX IDX_PROP_PRICE ON PROPERTIES(PRICE);
CREATE INDEX IDX_USER_EMAIL ON USERS(EMAIL);

-- PRODUCTS Table
CREATE TABLE PRODUCTS (
    ID VARCHAR2(36) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    PRICE NUMBER NOT NULL,
    CATEGORY VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add sample order table to satisfy the request example
CREATE TABLE ORDERS (
    ID VARCHAR2(36) PRIMARY KEY,
    USER_ID VARCHAR2(36) NOT NULL,
    PROPERTY_ID VARCHAR2(36),
    PRODUCT_ID VARCHAR2(36),
    AMOUNT NUMBER NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'pending',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_PROP FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTIES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE
);

-- ANALYTICS_REPORTS Table
CREATE TABLE ANALYTICS_REPORTS (
    ID VARCHAR2(36) PRIMARY KEY,
    REPORT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_USERS NUMBER,
    TOTAL_ORDERS NUMBER,
    REVENUE NUMBER,
    TOP_PRODUCT VARCHAR2(100),
    PREDICTED_SALES NUMBER,
    CHURN_RATE NUMBER,
    ANOMALIES_DETECTED CLOB,
    CONVERSION_RATE NUMBER,
    RETENTION_RATE NUMBER
);

-- MESSAGES Table
CREATE TABLE MESSAGES (
    ID VARCHAR2(36) PRIMARY KEY,
    SENDER_ID VARCHAR2(36) NOT NULL,
    RECIPIENT_ID VARCHAR2(36) NOT NULL,
    CONTENT CLOB,
    MESSAGE_TYPE VARCHAR2(20) DEFAULT 'text',
    MEDIA_URL VARCHAR2(255),
    PROPERTY_ID VARCHAR2(36),
    IS_READ NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MSG_SENDER FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSG_RECIPIENT FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSG_PROP FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTIES(ID) ON DELETE SET NULL
);

CREATE INDEX IDX_MSG_SENDER ON MESSAGES(SENDER_ID);
CREATE INDEX IDX_MSG_RECIPIENT ON MESSAGES(RECIPIENT_ID);

-- NOTIFICATIONS Table
CREATE TABLE NOTIFICATIONS (
    ID VARCHAR2(36) PRIMARY KEY,
    RECIPIENT_ID VARCHAR2(36) NOT NULL,
    SENDER_ID VARCHAR2(36),
    PROPERTY_ID VARCHAR2(36),
    NOTIF_TYPE VARCHAR2(20),
    MESSAGE VARCHAR2(255),
    IS_READ NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NOTIF_RECIP FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTIF_SENDER FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID) ON DELETE SET NULL,
    CONSTRAINT FK_NOTIF_PROP FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTIES(ID) ON DELETE SET NULL
);

CREATE INDEX IDX_NOTIF_RECIP ON NOTIFICATIONS(RECIPIENT_ID);
